// VS code extension: REST Client
// https://marketplace.visualstudio.com/items?itemName=humao.rest-client

// Test if the server is running
GET http://localhost:3001/

###

// List all the matchData currently in the database
GET http://localhost:3001/api/v1/matchData/2025

###

// List uniqueid in matchData currently in the database
GET http://localhost:3001/api/v1/matchData/2025/uniqueid/e576ae7b0b11df918ecfe669998af1f32b5394a6

###

// List match number in matchData currently in the database
GET http://localhost:3001/api/v1/matchData/2025/matchkey/2025mimil_qm1

###

// List match number in matchData currently in the database
GET http://localhost:3001/api/v1/matchData/2025/teamNumber/3641

###


// List match number in matchData currently in the database
GET http://localhost:3001/api/v1/matchData/2025/team/5561

###

// List the average matchData for all teams based on year and eventkey
// Following API replaced with GET http://localhost:3001/api/v1/matchData/2025/eventkey/2025mibel/exclude/0
# GET http://localhost:3001/api/v1/matchData/2025/eventkey/2025mibel

###

// List the average matchData for all team based on year and eventkey except for a list of teams
GET http://localhost:3001/api/v1/matchData/2025/eventkey/2025mibel/exclude/0

###

GET http://localhost:3001/api/v1/matchData/2026/1/team/1

// List matchData by ID 
GET http://localhost:3001/api/v1/matchData/2024/1

###

// Adds a matchData to the database
POST http://localhost:3001/api/v1/matchData/2025
content-type: application/json

{
    "scouterName": "Jane Doe",
    "matchNumber": 42,
    "teamNumber": 3641,
    "eventKey": "2024iawesdd",
    "matchKey": "2024iawesdd_qm42",
    "event_id": 1,
    "position": "R1",
    "uniqueId": "5fa49aa03512bcc45c2d46936c9301fb841d81aa"
}

###

// Adds a matchData to the database
DELETE http://localhost:3001/api/v1/matchData/2024/4


